### ISSUE TITLE
variables out of frame and hide variable dropdown choices

### ISSUE THREAD

**Issue by MaelLumenAI** [wearelumenai/bubbles4py#1]
When you click on a cluster with "a lot" of variables (actually 33 for me), the box containing all the variables grow up to the top, and thus hide the choice of variables

![image](https://user-images.githubusercontent.com/49390757/61306506-09804600-a7ed-11e9-827c-bdfd3c9e093e.png)

**Comment by ydarma** [comment]
Is there à notebook or an URL that would allow me to reproduce this case ?

**Comment by ydarma** [comment]
ok, I did it myself
https://luzine.lumenai.fr/notebooks/bubbles/bubbles4py-33.ipynb

**Comment by ydarma** [comment]
CSS fix.
